// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebRtcScreenShare.Infrastructure.Persistence;

#nullable disable

namespace WebRtcScreenShare.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260724102032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebRtcScreenShare.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$k.Mg5TTgYj3D8UJVx2e8Se/kQEuIRJvMCU0cP8fGPQ7q7USbXxVmK",
                            Role = "Sharer",
                            Username = "sharer1"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$k.Mg5TTgYj3D8UJVx2e8Se/kQEuIRJvMCU0cP8fGPQ7q7USbXxVmK",
                            Role = "Sharer",
                            Username = "sharer2"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "$2a$11$k.Mg5TTgYj3D8UJVx2e8Se/kQEuIRJvMCU0cP8fGPQ7q7USbXxVmK",
                            Role = "Viewer",
                            Username = "viewer1"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = "$2a$11$k.Mg5TTgYj3D8UJVx2e8Se/kQEuIRJvMCU0cP8fGPQ7q7USbXxVmK",
                            Role = "Viewer",
                            Username = "viewer2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
